name: omniboost
channels:
  - pytorch
  - plotly
  - nvidia
  - anaconda
  - defaults
dependencies:
  - asttokens=2.0.5
  - autopep8=1.6.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cuda-cccl=12.1.55
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.1.55
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.9.0
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9b
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - kiwisolver=1.4.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.0.8
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - plotly=5.14.0
  - prompt-toolkit=3.0.36
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywin32=305
  - pyzmq=23.2.0
  - qt=5.9.7
  - requests=2.28.1
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.2.0
  - sympy=1.11.1
  - tenacity=8.0.1
  - tk=8.6.7
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - tzdata=2022a
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - ale-py==0.8.1
      - ansicon==1.89.0
      - anyio==3.6.2
      - appdirs==1.4.4
      - arrow==1.2.3
      - async-timeout==4.0.2
      - atomicwrites==1.4.1
      - attrs==22.2.0
      - beautifulsoup4==4.12.0
      - blessed==1.20.0
      - box2d-py==2.3.5
      - cachetools==5.3.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - croniter==1.3.8
      - cython==0.29.33
      - dateutils==0.6.12
      - decorator==4.4.2
      - deepdiff==6.3.0
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - einops==0.6.0
      - email-validator==1.3.1
      - fastapi==0.88.0
      - fasteners==0.18
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.9
      - google-auth==2.17.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.53.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.26.3
      - gymnasium-notices==0.0.1
      - h11==0.14.0
      - httpcore==0.16.3
      - httptools==0.5.0
      - httpx==0.23.3
      - imageio==2.27.0
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - inquirer==3.1.3
      - itsdangerous==2.1.2
      - jinxed==1.2.0
      - joblib==1.2.0
      - lightning==2.0.1
      - lightning-cloud==0.5.32
      - lightning-utilities==0.8.0
      - lz4==4.3.2
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mujoco==2.2.0
      - mujoco-py==2.1.2.14
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - natsort==8.3.1
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - ordered-set==4.1.0
      - orjson==3.8.9
      - pathtools==0.1.2
      - pluggy==1.0.0
      - proglog==0.1.10
      - protobuf==4.22.1
      - psutil==5.9.4
      - py==1.11.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==1.10.7
      - pygame==2.1.0
      - pygments==2.14.0
      - pyjwt==2.6.0
      - pyopengl==3.1.6
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.11.1
      - pyre-extensions==0.0.30
      - pytest==7.0.1
      - python-dotenv==1.0.0
      - python-editor==1.0.4
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.1
      - pyyaml==6.0
      - readchar==4.0.5
      - requests-oauthlib==1.3.1
      - rfc3986==1.5.0
      - rich==13.3.3
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.18.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4
      - starlette==0.22.0
      - starsessions==1.3.0
      - swig==4.1.1
      - tensorboard==2.12.1
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - torchaudio==2.0.0
      - torchmetrics==0.11.4
      - torchsummary==1.5.1
      - torchtnt==0.0.7
      - torchvision==0.15.0
      - tqdm==4.65.0
      - typing-inspect==0.8.0
      - ujson==5.7.0
      - uvicorn==0.21.1
      - wandb==0.14.0
      - watchfiles==0.19.0
      - websocket-client==1.5.1
      - websockets==11.0
      - werkzeug==2.2.3
      - yarl==1.8.2
      - zipp==3.15.0
